"""RTKLIB provenance, configuration and process execution."""

from __future__ import annotations

import shutil
import subprocess
import time
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from nlgcp_single_base.io import sha256_file
from nlgcp_single_base.models import ProcessingMode, StationCoordinate

RECORDED_RTKLIB_REPOSITORY = "https://github.com/tomojitakasu/RTKLIB"
RECORDED_RTKLIB_TAG = "v2.4.2-p13"
RECORDED_RTKLIB_COMMIT = "71db0ffa0d9735697c6adfd06fdf766d0e5ce807"
RECORDED_RNX2RTKP_SHA256 = "b4a96cd0d5ffc00b44dab3a4fda214318c9f69cccee52128aec8bc26ad4f7d21"


@dataclass(frozen=True)
class RtklibProvenance:
    """Recorded provenance for the executable used by an experiment."""

    repository: str
    tag: str
    commit: str
    binary_path: Path
    binary_sha256: str
    help_probe: str
    matches_recorded_phase1_binary: bool


@dataclass(frozen=True)
class Rnx2RtkpExecution:
    """Subprocess execution provenance for one RTKLIB run."""

    command: list[str]
    return_code: int
    duration_seconds: float
    timeout_seconds: float
    stdout_path: Path
    stderr_path: Path


def capture_rtklib_provenance(binary_name: str = "rnx2rtkp") -> RtklibProvenance:
    """Locate and hash rnx2rtkp without upgrading or replacing it."""

    binary = shutil.which(binary_name)
    if binary is None:
        raise FileNotFoundError(f"{binary_name} was not found on PATH")
    binary_path = Path(binary).resolve()
    binary_sha256 = sha256_file(binary_path)
    probe = subprocess.run(
        [str(binary_path), "-h"],
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    return RtklibProvenance(
        repository=RECORDED_RTKLIB_REPOSITORY,
        tag=RECORDED_RTKLIB_TAG,
        commit=RECORDED_RTKLIB_COMMIT,
        binary_path=binary_path,
        binary_sha256=binary_sha256,
        help_probe=probe.stdout.strip(),
        matches_recorded_phase1_binary=binary_sha256 == RECORDED_RNX2RTKP_SHA256,
    )


def assert_recorded_rtklib(provenance: RtklibProvenance) -> None:
    """Stop scientific execution if the installed RTKLIB binary has drifted."""

    if not provenance.matches_recorded_phase1_binary:
        raise RuntimeError(
            "Installed rnx2rtkp SHA-256 does not match recorded Phase 1 provenance: "
            f"{provenance.binary_sha256}"
        )


def render_rtklib_config(
    mode: ProcessingMode,
    base_coordinate: StationCoordinate,
    *,
    navsys: str = "1",
    frequency: str = "l1+l2",
    elevation_mask_deg: float = 15.0,
    ambiguity_mode: str = "continuous",
) -> str:
    """Render a minimal, versioned RTKLIB configuration for single-base RTK."""

    pos_mode = "static" if mode is ProcessingMode.STATIC else "kinematic"
    base_ecef = base_coordinate.require_verified_ecef()
    return "\n".join(
        [
            "# NLGCP Phase 3 single-base RTKLIB configuration",
            "# Generated by research/single_base_rtk; review before scientific publication.",
            "# RTKLIB v2.4.2-p13 option names verified in src/options.c.",
            "# Initial benchmark assumptions; do not tune these to manufacture FIX.",
            f"# pos1-frequency={frequency} follows RTKLIB L1/L2 example defaults.",
            f"# pos1-elmask={elevation_mask_deg:g} deg follows rnx2rtkp CLI default.",
            f"# pos1-navsys={navsys} is GPS-only until Phase 2 establishes more systems.",
            f"# pos2-armode={ambiguity_mode} follows RTKLIB continuous AR option.",
            f"pos1-posmode       ={pos_mode}",
            f"pos1-frequency     ={frequency}",
            "pos1-soltype       =forward",
            f"pos1-elmask        ={elevation_mask_deg:g}",
            f"pos1-navsys        ={navsys}",
            f"pos2-armode        ={ambiguity_mode}",
            "out-solformat      =llh",
            "out-outhead        =on",
            "out-outopt         =on",
            "out-timesys        =gpst",
            "out-timeform       =hms",
            "out-timendec       =3",
            "out-degform        =deg",
            "out-height         =ellipsoidal",
            "stats-eratio1      =100",
            "ant2-postype       =xyz",
            f"ant2-pos1          ={base_ecef.x_m:.4f}",
            f"ant2-pos2          ={base_ecef.y_m:.4f}",
            f"ant2-pos3          ={base_ecef.z_m:.4f}",
            "",
        ]
    )


def run_rnx2rtkp(
    provenance: RtklibProvenance,
    config_path: Path,
    rover_observation: Path,
    base_observation: Path,
    navigation_paths: list[Path],
    output_path: Path,
    stdout_path: Path,
    stderr_path: Path,
    start_time_utc: str,
    end_time_utc: str,
    base_coordinate: StationCoordinate,
    timeout_seconds: float = 300.0,
) -> Rnx2RtkpExecution:
    """Run RTKLIB and preserve raw output streams."""

    base_ecef = base_coordinate.require_verified_ecef()
    command = [
        str(provenance.binary_path),
        "-k",
        str(config_path),
        "-ts",
        *_rtklib_epoch_args(start_time_utc),
        "-te",
        *_rtklib_epoch_args(end_time_utc),
        "-ti",
        "0",
        "-r",
        f"{base_ecef.x_m:.4f}",
        f"{base_ecef.y_m:.4f}",
        f"{base_ecef.z_m:.4f}",
        "-o",
        str(output_path),
        str(rover_observation),
        str(base_observation),
        *[str(path) for path in navigation_paths],
    ]
    started = time.monotonic()
    result = subprocess.run(
        command,
        check=False,
        text=True,
        capture_output=True,
        timeout=timeout_seconds,
    )
    duration_seconds = time.monotonic() - started
    stdout_path.write_text(result.stdout, encoding="utf-8")
    stderr_path.write_text(result.stderr, encoding="utf-8")
    return Rnx2RtkpExecution(
        command=command,
        return_code=result.returncode,
        duration_seconds=duration_seconds,
        timeout_seconds=timeout_seconds,
        stdout_path=stdout_path,
        stderr_path=stderr_path,
    )


def execution_json(execution: Rnx2RtkpExecution) -> dict[str, Any]:
    """Convert execution provenance to JSON-safe values."""

    return {
        "command": execution.command,
        "return_code": execution.return_code,
        "duration_seconds": execution.duration_seconds,
        "timeout_seconds": execution.timeout_seconds,
        "stdout_path": execution.stdout_path,
        "stderr_path": execution.stderr_path,
    }


def _rtklib_epoch_args(timestamp: str) -> tuple[str, str]:
    value = timestamp.replace("Z", "+00:00")
    parsed = datetime.fromisoformat(value)
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=UTC)
    parsed = parsed.astimezone(UTC)
    return parsed.strftime("%Y/%m/%d"), parsed.strftime("%H:%M:%S")
